package trainer

// =============================================================================
// EDITING & UNDO MODULE EXERCISES
// =============================================================================

// getEditingLessons returns the lessons for the Editing & Undo module. Every
// lesson opts into the buffer judge (Exercise.BufferVerified): the module exists
// to teach that an editing command is judged by the state it leaves behind, not
// by the keys pressed. The missions therefore state a result -- a buffer, a
// cursor, a mode -- and the optimal shows the canonical keystrokes that reach
// it. All of them were verified against the engine in editor.go.
func getEditingLessons() []Exercise {
	return []Exercise{
		// Lesson 1 (level 1): u undoes the last normal-mode command.
		{
			ID:     "editing_001",
			Module: ModuleEditing,
			Level:  1,
			Type:   ExerciseLesson,
			Code: []string{
				"local count = 0",
				"local total = 10",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Delete the first character with x, then undo it with u. The buffer must be exactly as it started, with the cursor at the start of line 1.",
			Solutions:      []string{"xu", "ddu"},
			Optimal:        "xu",
			Hint:           "x changes the buffer, so one u restores the line exactly as it was.",
			Explanation:    "u undoes the last change. x deleted a character, so u restores the buffer and the cursor to what they were before the command. ddu is accepted too: ddu reaches the same buffer and cursor by a different route, which is exactly what the buffer judge checks.",
			TimeoutSecs:    30,
			Points:         10,
			BufferVerified: true,
		},
		// Lesson 2 (level 1): dd deletes the whole line.
		{
			ID:     "editing_002",
			Module: ModuleEditing,
			Level:  1,
			Type:   ExerciseLesson,
			Code: []string{
				"keep this",
				"delete me",
				"keep this too",
			},
			CursorPos:      Position{Line: 1, Col: 0},
			Mission:        "Delete line 2 with dd. The buffer must be 'keep this', 'keep this too' with the cursor at the start of the new line 2.",
			Solutions:      []string{"dd"},
			Optimal:        "dd",
			Hint:           "dd removes the whole line, unlike D which stops at the end of it.",
			Explanation:    "dd deletes the line under the cursor and lands on the first non-blank of the line that takes its place. It is the line-level delete every editing session uses.",
			TimeoutSecs:    30,
			Points:         10,
			BufferVerified: true,
		},
		// Lesson 3 (level 1): x with a count.
		{
			ID:     "editing_003",
			Module: ModuleEditing,
			Level:  1,
			Type:   ExerciseLesson,
			Code: []string{
				"const value = 0;",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Delete the first six characters 'const ' with a single counted command. The line must read 'value = 0;'.",
			Solutions:      []string{"6x", "xxxxxx"},
			Optimal:        "6x",
			Hint:           "x takes a count: 6x deletes six characters in one command.",
			Explanation:    "x deletes the character under the cursor; a count deletes that many. 6x and xxxxxx leave the same buffer and cursor, and the buffer judge accepts both.",
			TimeoutSecs:    30,
			Points:         10,
			BufferVerified: true,
		},
		// Lesson 4 (level 2): Ctrl-r redoes.
		{
			ID:     "editing_004",
			Module: ModuleEditing,
			Level:  2,
			Type:   ExerciseLesson,
			Code: []string{
				"const a = 1;",
				"const b = 2;",
				"const c = 3;",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Delete line 1 with dd, undo it with u, then redo it with Ctrl-r. The buffer must end without line 1 and the cursor must be at the start of the new line 1.",
			Solutions:      []string{"ddu\x12", "dd"},
			Optimal:        "ddu\x12",
			Hint:           "Ctrl-r redoes what u undid, one change at a time: 3Ctrl-r redoes three.",
			Explanation:    "Ctrl-r is the inverse of u: it reapplies the most recently undone change. ddu<Ctrl-r> ends in the same state as a plain dd, which is why both are accepted.",
			TimeoutSecs:    30,
			Points:         10,
			BufferVerified: true,
		},
		// Lesson 5 (level 2): i inserts before the cursor.
		{
			ID:     "editing_005",
			Module: ModuleEditing,
			Level:  2,
			Type:   ExerciseLesson,
			Code: []string{
				"    count = 0",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Insert 'the ' at the very start of the line with i, before the indentation, then leave insert mode. The line must read 'the     count = 0'.",
			Solutions:      []string{"ithe <Esc>"},
			Optimal:        "ithe <Esc>",
			Hint:           "i starts insert mode at the cursor. Ctrl-e types the <Esc> the trainer needs to leave insert mode.",
			Explanation:    "i inserts before the character under the cursor. Here the cursor sits on the first space, so the text goes in ahead of the indentation. The engine treats the whole insert session as one change.",
			TimeoutSecs:    30,
			Points:         10,
			BufferVerified: true,
		},
		// Lesson 6 (level 2): a appends after the cursor.
		{
			ID:     "editing_006",
			Module: ModuleEditing,
			Level:  2,
			Type:   ExerciseLesson,
			Code: []string{
				"    count = 0",
			},
			CursorPos:      Position{Line: 0, Col: 8},
			Mission:        "Append an 's' directly after the cursor with a, then leave insert mode. The line must read '    counts = 0'.",
			Solutions:      []string{"as<Esc>"},
			Optimal:        "as<Esc>",
			Hint:           "a appends after the cursor, so one key carries on where i would insert before it.",
			Explanation:    "a enters insert mode after the character under the cursor, so typing 's' right after the 't' turns 'count' into 'counts'. Use i when you want to insert before the cursor instead.",
			TimeoutSecs:    30,
			Points:         10,
			BufferVerified: true,
		},
		// Lesson 7 (level 2): D deletes to the end of the line.
		{
			ID:     "editing_007",
			Module: ModuleEditing,
			Level:  2,
			Type:   ExerciseLesson,
			Code: []string{
				"remove everything",
				"keep this",
			},
			CursorPos:      Position{Line: 0, Col: 6},
			Mission:        "Delete from the cursor to the end of the line with D. The first line must become 'remove' and the second must stay 'keep this'.",
			Solutions:      []string{"D"},
			Optimal:        "D",
			Hint:           "D deletes to the end of the line in one key, so no motion follows it.",
			Explanation:    "D deletes from the cursor to the end of the line without touching the lines below it. The cursor stops on the last remaining character.",
			TimeoutSecs:    30,
			Points:         10,
			BufferVerified: true,
		},
		// Lesson 8 (level 2): >> indents.
		{
			ID:     "editing_008",
			Module: ModuleEditing,
			Level:  2,
			Type:   ExerciseLesson,
			Code: []string{
				"if true {",
				"return 1",
				"}",
			},
			CursorPos:      Position{Line: 1, Col: 0},
			Mission:        "Indent line 2 by one shift with >>. The line must read '  return 1'.",
			Solutions:      []string{">>"},
			Optimal:        ">>",
			Hint:           ">> takes a count and a range: 2>> indents two lines in one command.",
			Explanation:    ">> indents the current line by one shift (two spaces here). Its counterpart << dedents by the same amount, and both land the cursor on the first non-blank of the changed line.",
			TimeoutSecs:    30,
			Points:         10,
			BufferVerified: true,
		},
		// Lesson 9 (level 3): I inserts at the first non-blank.
		{
			ID:     "editing_009",
			Module: ModuleEditing,
			Level:  3,
			Type:   ExerciseLesson,
			Code: []string{
				"    count = 0",
			},
			CursorPos:      Position{Line: 0, Col: 8},
			Mission:        "Insert 'total = ' at the first non-blank character with I, then leave insert mode. The line must read '    total = count = 0'.",
			Solutions:      []string{"Itotal = <Esc>"},
			Optimal:        "Itotal = <Esc>",
			Hint:           "I lands after the indentation, where 0 would stop at column 0.",
			Explanation:    "I is i at the first non-blank of the line, so it keeps the indentation intact. It is the fastest way to prepend to an indented line without retyping its spaces.",
			TimeoutSecs:    30,
			Points:         15,
			BufferVerified: true,
		},
		// Lesson 10 (level 3): A appends at the end of the line.
		{
			ID:     "editing_010",
			Module: ModuleEditing,
			Level:  3,
			Type:   ExerciseLesson,
			Code: []string{
				"    count = 0",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Append ' // tally' at the very end of the line with A, then leave insert mode. The line must read '    count = 0 // tally'.",
			Solutions:      []string{"A // tally<Esc>"},
			Optimal:        "A // tally<Esc>",
			Hint:           "A goes to the end of the line and starts insert mode, so one keystroke replaces $ then a.",
			Explanation:    "A is a at end-of-line: it appends without you having to move the cursor first. a only inserts after the current character, so A is what you want for a trailing comment.",
			TimeoutSecs:    30,
			Points:         15,
			BufferVerified: true,
		},
		// Lesson 11 (level 3): o opens a line below.
		{
			ID:     "editing_011",
			Module: ModuleEditing,
			Level:  3,
			Type:   ExerciseLesson,
			Code: []string{
				"func main() {",
				"}",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Open a new line below line 1 with o and type '  return', then leave insert mode. The buffer must be three lines with '  return' in the middle.",
			Solutions:      []string{"o  return<Esc>"},
			Optimal:        "o  return<Esc>",
			Hint:           "o opens the line below and leaves you in insert mode, so the new line keeps the current indent.",
			Explanation:    "o opens a line below the current one and enters insert mode, so you can create and fill a line in one motion. The new line inherits the current line's indentation.",
			TimeoutSecs:    30,
			Points:         15,
			BufferVerified: true,
		},
		// Lesson 12 (level 3): O opens a line above.
		{
			ID:     "editing_012",
			Module: ModuleEditing,
			Level:  3,
			Type:   ExerciseLesson,
			Code: []string{
				"func main() {",
				"  return",
				"}",
			},
			CursorPos:      Position{Line: 1, Col: 0},
			Mission:        "Open a new line above line 2 with O and type 'x := 1'. It must inherit the two-space indentation: the buffer must read func main() {, '  x := 1', '  return', }.",
			Solutions:      []string{"Ox := 1<Esc>"},
			Optimal:        "Ox := 1<Esc>",
			Hint:           "O opens a new line above the cursor, inheriting the line's indentation.",
			Explanation:    "O is o's mirror: it opens a line above the current one. Both inherit the auto-indentation of the line they were opened from, so the new line already sits at the right level.",
			TimeoutSecs:    30,
			Points:         15,
			BufferVerified: true,
		},
		// Lesson 13 (level 3): a counted line delete.
		{
			ID:     "editing_013",
			Module: ModuleEditing,
			Level:  3,
			Type:   ExerciseLesson,
			Code: []string{
				"a",
				"b",
				"c",
				"d",
			},
			CursorPos:      Position{Line: 1, Col: 0},
			Mission:        "Delete lines 2 and 3 in a single command with a count. The buffer must be 'a', 'd' with the cursor on 'd'.",
			Solutions:      []string{"2dd", "dddd"},
			Optimal:        "2dd",
			Hint:           "dd takes a count: 2dd deletes two lines.",
			Explanation:    "2dd deletes two lines at once, and two separate dd commands land in the same place. Counts apply to most editing commands, which is how you avoid repeating yourself.",
			TimeoutSecs:    30,
			Points:         15,
			BufferVerified: true,
		},
		// Lesson 14 (level 3): yy and p.
		{
			ID:     "editing_014",
			Module: ModuleEditing,
			Level:  3,
			Type:   ExerciseLesson,
			Code: []string{
				"alpha",
				"beta",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Yank line 1 with yy, move down with j, and paste it below line 2 with p. The buffer must be alpha, beta, alpha.",
			Solutions:      []string{"yyjp"},
			Optimal:        "yyjp",
			Hint:           "yy copies the line and p puts it below, so the copy lands under the line it came from.",
			Explanation:    "yy copies the current line into a register without changing the buffer. p pastes the register below the cursor's line, so yyjp duplicates the first line at the end.",
			TimeoutSecs:    30,
			Points:         15,
			BufferVerified: true,
		},
		// Lesson 15 (level 4): an empty line opened with o and left immediately.
		{
			ID:     "editing_015",
			Module: ModuleEditing,
			Level:  4,
			Type:   ExerciseLesson,
			Code: []string{
				"func main() {",
				"  return",
			},
			CursorPos:      Position{Line: 1, Col: 0},
			Mission:        "Open a new empty line below line 2 with o and leave insert mode immediately with <Esc>. The buffer must have an empty line between the two.",
			Solutions:      []string{"o<Esc>"},
			Optimal:        "o<Esc>",
			Hint:           "o copies the current indentation, so an immediate <Esc> leaves the new line empty.",
			Explanation:    "Opening a line with o and leaving without typing keeps the new (empty) line but removes the indentation it started with. That is why the buffer gains an empty line without any trailing spaces.",
			TimeoutSecs:    30,
			Points:         15,
			BufferVerified: true,
		},
		// Lesson 16 (level 4): each normal-mode command is one undo step.
		{
			ID:     "editing_016",
			Module: ModuleEditing,
			Level:  4,
			Type:   ExerciseLesson,
			Code: []string{
				"hello world",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Delete the first character twice with x x, then undo both deletions with u u. The buffer must be exactly as it started.",
			Solutions:      []string{"xxuu"},
			Optimal:        "xxuu",
			Hint:           "Each normal-mode command is its own undo step, so two deletions need two undos.",
			Explanation:    "Undo granularity is one step per normal-mode command: x x records two snapshots, so it takes u u to get back. A single u would leave the line one character shorter.",
			TimeoutSecs:    30,
			Points:         15,
			BufferVerified: true,
		},
		// Lesson 17 (level 4): a whole insert session undoes in one step.
		{
			ID:     "editing_017",
			Module: ModuleEditing,
			Level:  4,
			Type:   ExerciseLesson,
			Code: []string{
				"one",
				"two",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Append '!' to line 1 with A <Esc>. Then open a line below with o, type 'junk', and leave with <Esc>. Undo once: the junk line must vanish whole while line 1 stays 'one!'. The buffer must be 'one!', 'two'.",
			Solutions:      []string{"A!<Esc>ojunk<Esc>u", "A!<Esc>"},
			Optimal:        "A!<Esc>ojunk<Esc>u",
			Hint:           "An insert session is one change, so a single u removes the whole 'junk' line.",
			Explanation:    "Everything typed between entering insert mode and leaving it is one undo step, so one u removes the line o opened and the text typed on it together. The earlier '!' edit survives because it was a separate session.",
			TimeoutSecs:    45,
			Points:         20,
			BufferVerified: true,
		},
		// Lesson 18 (level 4): a counted dedent.
		{
			ID:     "editing_018",
			Module: ModuleEditing,
			Level:  4,
			Type:   ExerciseLesson,
			Code: []string{
				"    return 1",
				"    return 2",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Dedent both lines at once with a count. The lines must read '  return 1' and '  return 2'.",
			Solutions:      []string{"2<<"},
			Optimal:        "2<<",
			Hint:           "<< dedents the current line; 2<< dedents two.",
			Explanation:    "<< removes one shift of indentation from the current line, and the count applies it to the lines below as well. Two shifts are removed from the two-space indent, leaving two spaces.",
			TimeoutSecs:    45,
			Points:         20,
			BufferVerified: true,
		},
		// Lesson 19 (level 5): redo a whole insert session.
		{
			ID:     "editing_019",
			Module: ModuleEditing,
			Level:  5,
			Type:   ExerciseLesson,
			Code: []string{
				"first",
				"second",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Open a line below line 1 with o, type 'middle', leave with <Esc>, undo with u, then redo with Ctrl-r. The buffer must read first, middle, second with the cursor at the start of line 1.",
			Solutions:      []string{"omiddle<Esc>u\x12", "omiddle<Esc>gg"},
			Optimal:        "omiddle<Esc>u\x12",
			Hint:           "Ctrl-r brings back the entire insert session at once; 2Ctrl-r redoes two undone changes.",
			Explanation:    "Redo is the inverse of undo at the same granularity: one Ctrl-r brings back the entire insert session. The redo restores the cursor the undo left, which is why the cursor ends at the start of line 1 rather than on 'middle'.",
			TimeoutSecs:    45,
			Points:         25,
			BufferVerified: true,
		},
		// Lesson 20 (level 5): the yank register 0 survives a delete.
		{
			ID:     "editing_020",
			Module: ModuleEditing,
			Level:  5,
			Type:   ExerciseLesson,
			Code: []string{
				"x",
				"y",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Yank line 1 with yy, delete line 2 with j dd, then paste register 0 below the cursor with \"0p. The buffer must be x, x.",
			Solutions:      []string{"yyjdd\"0p"},
			Optimal:        "yyjdd\"0p",
			Hint:           "Register 0 always holds the last yank, even after a delete overwrites the unnamed register.",
			Explanation:    "Every yank fills register 0, and a delete overwrites the unnamed register but not register 0. That is why \"0p pastes the yanked 'x' even though the last delete put 'y' in the unnamed register.",
			TimeoutSecs:    45,
			Points:         25,
			BufferVerified: true,
		},
		// Lesson 21 (level 6): dw deletes a word via a delegated motion.
		{
			ID:     "editing_021",
			Module: ModuleEditing,
			Level:  6,
			Type:   ExerciseLesson,
			Code: []string{
				"const value = 0;",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Delete the first word and its trailing space with dw. The line must read 'value = 0;'.",
			Solutions:      []string{"dw", "6x"},
			Optimal:        "dw",
			Hint:           "dw is the delete operator applied to the w motion.",
			Explanation:    "An operator takes a motion: dw deletes from the cursor to the start of the next word. Because the motion is delegated to the same parser the motion judge uses, dw affects exactly the range you would move over.",
			TimeoutSecs:    45,
			Points:         30,
			BufferVerified: true,
		},
		// Lesson 22 (level 6): % is a motion, so it composes with a change.
		{
			ID:     "editing_022",
			Module: ModuleEditing,
			Level:  6,
			Type:   ExerciseLesson,
			Code: []string{
				"let x = (a);",
			},
			CursorPos:      Position{Line: 0, Col: 8},
			Mission:        "With the cursor on the '(', jump to the matching ')' with % and then delete that character with x. The line must read 'let x = (a;'.",
			Solutions:      []string{"%x"},
			Optimal:        "%x",
			Hint:           "% jumps to the bracket matching the one under the cursor, so put the cursor on the '(' first.",
			Explanation:    "% finds the bracket matching the one under the cursor. Because it only moves the cursor, it composes with any command, so %x jumps to the closer and deletes it.",
			TimeoutSecs:    45,
			Points:         30,
			BufferVerified: true,
		},
		// Lesson 23 (level 8): marks follow the text through a delete.
		{
			ID:     "editing_023",
			Module: ModuleEditing,
			Level:  8,
			Type:   ExerciseLesson,
			Code: []string{
				"alpha",
				"beta",
				"gamma",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Go to line 3 with G, set mark a with ma, return to line 1 with gg, delete line 1 with dd, then jump to the mark with `a. The cursor must land on 'gamma'.",
			Solutions:      []string{"Gmaggdd`a", "ddG"},
			Optimal:        "Gmaggdd`a",
			Hint:           "A mark sticks to its line, so deleting a line above it moves it up with the text.",
			Explanation:    "ma records a position in a mark, and `a jumps back to it. Marks are attached to lines, so deleting line 1 shifts mark a up with its text; that is what makes `a land on 'gamma' after the delete.",
			TimeoutSecs:    45,
			Points:         40,
			BufferVerified: true,
		},
	}
}

func getEditingBoss() *BossExercise {
	return &BossExercise{
		ID:        "editing_boss",
		Module:    ModuleEditing,
		Name:      "The Historian",
		Lives:     3,
		BonusTime: 30,
		Steps: []BossStep{
			{
				TimeLimit: 8,
				Exercise: Exercise{
					ID:     "editing_boss_1",
					Module: ModuleEditing,
					Level:  5,
					Type:   ExerciseBoss,
					Code: []string{
						"alpha",
						"beta",
						"gamma",
					},
					CursorPos:      Position{Line: 0, Col: 0},
					Mission:        "Delete line 2 with j dd, undo it with u, then redo it with Ctrl-r. The buffer must read alpha, gamma with the cursor at the start of line 2.",
					Solutions:      []string{"jddu\x12", "jdd"},
					Optimal:        "jddu\x12",
					Points:         50,
					BufferVerified: true,
				},
			},
			{
				TimeLimit: 10,
				Exercise: Exercise{
					ID:     "editing_boss_2",
					Module: ModuleEditing,
					Level:  6,
					Type:   ExerciseBoss,
					Code: []string{
						"start",
						"end",
					},
					CursorPos:      Position{Line: 0, Col: 0},
					Mission:        "Open a line below line 1 with o, type 'temp', leave with <Esc>, undo it with u, then open a line above line 1 with O and type 'kept'. The buffer must read kept, start, end.",
					Solutions:      []string{"otemp<Esc>uOkept<Esc>", "Okept<Esc>"},
					Optimal:        "otemp<Esc>uOkept<Esc>",
					Points:         50,
					BufferVerified: true,
				},
			},
			{
				TimeLimit: 10,
				Exercise: Exercise{
					ID:     "editing_boss_3",
					Module: ModuleEditing,
					Level:  6,
					Type:   ExerciseBoss,
					Code: []string{
						"one",
						"two",
					},
					CursorPos:      Position{Line: 0, Col: 0},
					Mission:        "Yank line 1 with yy, delete line 2 with j dd, then paste register 0 below the cursor with \"0p. The buffer must be one, one.",
					Solutions:      []string{"yyjdd\"0p"},
					Optimal:        "yyjdd\"0p",
					Points:         50,
					BufferVerified: true,
				},
			},
			{
				TimeLimit: 12,
				Exercise: Exercise{
					ID:     "editing_boss_4",
					Module: ModuleEditing,
					Level:  7,
					Type:   ExerciseBoss,
					Code: []string{
						"fn main() {",
						"    println!(\"hi\");",
						"}",
					},
					CursorPos:      Position{Line: 1, Col: 0},
					Mission:        "Indent line 2 with >> and then delete it with dd, leaving the braces adjacent. The buffer must read 'fn main() {' then '}'.",
					Solutions:      []string{">>dd", "dd"},
					Optimal:        ">>dd",
					Points:         50,
					BufferVerified: true,
				},
			},
			{
				TimeLimit: 15,
				Exercise: Exercise{
					ID:     "editing_boss_5",
					Module: ModuleEditing,
					Level:  7,
					Type:   ExerciseBoss,
					Code: []string{
						"alpha",
						"beta",
						"gamma",
						"delta",
					},
					CursorPos:      Position{Line: 0, Col: 0},
					Mission:        "Go to line 4 with G, set mark a with ma, return to line 1 with gg, delete line 1 with dd, jump to the mark with `a, then delete the character under the cursor with x. The buffer must read beta, gamma, 'elta' with the cursor at the start of the last line.",
					Solutions:      []string{"Gmaggdd`ax"},
					Optimal:        "Gmaggdd`ax",
					Points:         50,
					BufferVerified: true,
				},
			},
		},
	}
}
