package trainer

// =============================================================================
// REGISTERS & INDENTATION MODULE EXERCISES
// =============================================================================

// getRegistersLessons returns the lessons for the Registers & Indentation
// module. Every lesson opts into the buffer judge (Exercise.BufferVerified), so
// every mission states a result the judge can check -- a buffer, a cursor, a
// mode -- rather than the keys that reach it. The arc walks the two ideas the
// engine supports and nothing taught: a yank and a delete both fill a register,
// which is why p and P put back the last thing removed, and indentation is a
// shift applied to the line under the cursor, a counted range from it, or a
// named register that survives the deletions passing through the unnamed one.
// All of the optimal answers were verified against the engine in editor.go.
func getRegistersLessons() []Exercise {
	return []Exercise{
		// Lesson 1 (level 1): yank a line and put it below.
		{
			ID:     "registers_001",
			Module: ModuleRegisters,
			Level:  1,
			Type:   ExerciseLesson,
			Code: []string{
				"alpha",
				"beta",
				"gamma",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Yank line 1 with yy and put a copy of it below with p. The buffer must read alpha, alpha, beta, gamma with the cursor at the start of the copy.",
			Solutions:      []string{"yyp"},
			Optimal:        "yyp",
			Hint:           "yy copies the current line; p puts it below the cursor's line.",
			Explanation:    "yy fills a register with line 1 without changing the buffer, and p puts the register's lines below the cursor's line. The cursor lands on the first non-blank of the put line, which is where the copy begins.",
			TimeoutSecs:    30,
			Points:         10,
			BufferVerified: true,
		},
		// Lesson 2 (level 1): yank a line and put it above.
		{
			ID:     "registers_002",
			Module: ModuleRegisters,
			Level:  1,
			Type:   ExerciseLesson,
			Code: []string{
				"alpha",
				"beta",
			},
			CursorPos:      Position{Line: 1, Col: 0},
			Mission:        "Yank line 2 with yy and put a copy of it above with P. The buffer must read alpha, beta, beta with the cursor at the start of the first beta.",
			Solutions:      []string{"yyP"},
			Optimal:        "yyP",
			Hint:           "P puts the register above the cursor's line; p puts it below.",
			Explanation:    "P is p's mirror: it inserts the register's lines above the cursor's line. The linewise flag is what decides the position -- the same register that p puts below, P puts above.",
			TimeoutSecs:    30,
			Points:         10,
			BufferVerified: true,
		},
		// Lesson 3 (level 2): yank a word and put it before the cursor.
		{
			ID:     "registers_003",
			Module: ModuleRegisters,
			Level:  2,
			Type:   ExerciseLesson,
			Code: []string{
				"total = a",
			},
			CursorPos:      Position{Line: 0, Col: 8},
			Mission:        "Yank the operand 'a' with yiw and put a second copy of it before the cursor with P. The line must read 'total = aa'.",
			Solutions:      []string{"yiwP"},
			Optimal:        "yiwP",
			Hint:           "yiw yanks the inner word; a word is character-wise, so P inserts it before the cursor's character.",
			Explanation:    "yiw fills the register with the word under the cursor as character-wise text. P inserts character-wise text before the character under the cursor, so the copy lands immediately to the left of the first 'a' and the line reads 'total = aa'.",
			TimeoutSecs:    30,
			Points:         10,
			BufferVerified: true,
		},
		// Lesson 4 (level 2): yank a word and put it after the cursor.
		{
			ID:     "registers_004",
			Module: ModuleRegisters,
			Level:  2,
			Type:   ExerciseLesson,
			Code: []string{
				"x = a",
			},
			CursorPos:      Position{Line: 0, Col: 4},
			Mission:        "Yank the operand 'a' with yiw and put a copy of it after the cursor with p. The line must read 'x = aa'.",
			Solutions:      []string{"yiwp"},
			Optimal:        "yiwp",
			Hint:           "For character-wise text p inserts after the cursor's character, one column right of where P would.",
			Explanation:    "p and P differ by the put position and by nothing else: p inserts after the cursor's character, P before it. Both leave the cursor on the last character they inserted, so p ends one column right of P.",
			TimeoutSecs:    30,
			Points:         10,
			BufferVerified: true,
		},
		// Lesson 5 (level 2): dd then p moves a line down.
		{
			ID:     "registers_005",
			Module: ModuleRegisters,
			Level:  2,
			Type:   ExerciseLesson,
			Code: []string{
				"one",
				"two",
				"three",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Move line 1 below line 2: delete it with dd and put it back with p. The buffer must read two, one, three.",
			Solutions:      []string{"ddp"},
			Optimal:        "ddp",
			Hint:           "dd deletes the line into the register, so p puts that line back.",
			Explanation:    "This is the register model in one answer: a delete fills the same unnamed register a yank does. dd removes line 1 and leaves it in the register; p then puts it below the cursor's line, so the line travels down.",
			TimeoutSecs:    30,
			Points:         10,
			BufferVerified: true,
		},
		// Lesson 6 (level 2): dd then P moves a line up.
		{
			ID:     "registers_006",
			Module: ModuleRegisters,
			Level:  2,
			Type:   ExerciseLesson,
			Code: []string{
				"one",
				"two",
				"three",
			},
			CursorPos:      Position{Line: 2, Col: 0},
			Mission:        "Move line 3 above line 2: delete it with dd, then put it back above the cursor with P. The buffer must read one, three, two.",
			Solutions:      []string{"ddP"},
			Optimal:        "ddP",
			Hint:           "After dd the cursor sits on the line that took the deleted line's place; P puts the register above it.",
			Explanation:    "dd leaves the cursor on the line that replaced the deleted one. P then reinserts the deleted line above the cursor, so the line travels up instead of down. The same register and the same delete power both moves.",
			TimeoutSecs:    30,
			Points:         10,
			BufferVerified: true,
		},
		// Lesson 7 (level 3): a named register round trip.
		{
			ID:     "registers_007",
			Module: ModuleRegisters,
			Level:  3,
			Type:   ExerciseLesson,
			Code: []string{
				"alpha",
				"beta",
				"gamma",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Store line 1 in register a with \"ayy, move to line 2 with j, then put register a below it with \"ap. The buffer must read alpha, beta, alpha, gamma with the cursor at the start of the put line.",
			Solutions:      []string{"\"ayyj\"ap"},
			Optimal:        "\"ayyj\"ap",
			Hint:           "The \"a prefix names register a for both the yank and the put.",
			Explanation:    "A \"{name} prefix in front of a command selects the register it reads or writes, so \"ayy yanks into a and \"ap puts from a. The named register holds its own copy, which is what lets several yanks coexist.",
			TimeoutSecs:    45,
			Points:         15,
			BufferVerified: true,
		},
		// Lesson 8 (level 4): register 0 survives a delete.
		{
			ID:     "registers_008",
			Module: ModuleRegisters,
			Level:  4,
			Type:   ExerciseLesson,
			Code: []string{
				"x",
				"y",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Yank line 1 with yy, delete line 2 with j dd, then put register 0 below the cursor with \"0p. The buffer must read x, x: the delete overwrote the unnamed register but not register 0.",
			Solutions:      []string{"yyjdd\"0p"},
			Optimal:        "yyjdd\"0p",
			Hint:           "Register 0 always holds the last yank, even after a delete fills the unnamed register.",
			Explanation:    "Every yank fills register 0, and a delete overwrites the unnamed register but never register 0. This is the lesson that makes the register model worth learning: after j dd the unnamed register holds 'y', yet \"0p still pastes the yanked 'x'.",
			TimeoutSecs:    45,
			Points:         20,
			BufferVerified: true,
		},
		// Lesson 9 (level 3): a named register round trip through a delete.
		{
			ID:     "registers_009",
			Module: ModuleRegisters,
			Level:  3,
			Type:   ExerciseLesson,
			Code: []string{
				"alpha",
				"beta",
				"gamma",
			},
			CursorPos:      Position{Line: 1, Col: 0},
			Mission:        "Delete line 2 into register a with \"add, move up with k, then put it back with \"ap. The buffer must be exactly as it started, with the cursor at the start of line 2.",
			Solutions:      []string{"\"addk\"ap"},
			Optimal:        "\"addk\"ap",
			Hint:           "A named delete stores the line in register a so a later \"ap can restore it.",
			Explanation:    "A named register is safe storage: \"add deletes line 2 into a, and k moves the cursor up before \"ap puts it back exactly where it was. Because the named register is separate from the unnamed one, nothing the move does can clobber it.",
			TimeoutSecs:    45,
			Points:         15,
			BufferVerified: true,
		},
		// Lesson 10 (level 2): >> indents the current line.
		{
			ID:     "registers_010",
			Module: ModuleRegisters,
			Level:  2,
			Type:   ExerciseLesson,
			Code: []string{
				"return 1",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Indent the line by one shift with >>. The line must read '  return 1'.",
			Solutions:      []string{">>"},
			Optimal:        ">>",
			Hint:           ">> shifts the current line one 'shiftwidth' to the right.",
			Explanation:    ">> adds one shift of indentation -- two spaces here -- to the current line. The buffer changes but the line's text does not; only the leading whitespace is rewritten.",
			TimeoutSecs:    30,
			Points:         10,
			BufferVerified: true,
		},
		// Lesson 11 (level 2): << dedents the current line.
		{
			ID:     "registers_011",
			Module: ModuleRegisters,
			Level:  2,
			Type:   ExerciseLesson,
			Code: []string{
				"    return 1",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Dedent the line by one shift with <<. The line must read '  return 1'.",
			Solutions:      []string{"<<"},
			Optimal:        "<<",
			Hint:           "<< removes one shift of indentation from the current line.",
			Explanation:    "<< is >>'s inverse: it removes one shift from the current line, removing no more than the line actually has. The cursor stops on the first non-blank of the changed line.",
			TimeoutSecs:    30,
			Points:         10,
			BufferVerified: true,
		},
		// Lesson 12 (level 3): a counted shift right over a range.
		{
			ID:     "registers_012",
			Module: ModuleRegisters,
			Level:  3,
			Type:   ExerciseLesson,
			Code: []string{
				"if true {",
				"return 1",
				"return 2",
				"}",
			},
			CursorPos:      Position{Line: 1, Col: 0},
			Mission:        "Indent lines 2 and 3 as one range with 2>>. They must read '  return 1' and '  return 2'.",
			Solutions:      []string{"2>>"},
			Optimal:        "2>>",
			Hint:           "A count in front of >> applies the shift to that many lines, starting at the cursor.",
			Explanation:    "The count in 2>> turns the shift into a range: it indents the current line and the one below it, and the cursor stays on the first line of the range. The two lines still have to be shifted as one command.",
			TimeoutSecs:    45,
			Points:         15,
			BufferVerified: true,
		},
		// Lesson 13 (level 3): a counted shift left over a range.
		{
			ID:     "registers_013",
			Module: ModuleRegisters,
			Level:  3,
			Type:   ExerciseLesson,
			Code: []string{
				"    return 1",
				"    return 2",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Dedent both lines as one range with 2<<. They must read '  return 1' and '  return 2'.",
			Solutions:      []string{"2<<"},
			Optimal:        "2<<",
			Hint:           "2<< dedents the current line and the one below it in a single command.",
			Explanation:    "2<< applies the left shift to the two-line range that starts at the cursor. The count is what makes it a range rather than a single line, and the cursor lands on the first non-blank of the first shifted line.",
			TimeoutSecs:    45,
			Points:         15,
			BufferVerified: true,
		},
		// Lesson 14 (level 4): a counted shift over a range in the middle of the buffer.
		{
			ID:     "registers_014",
			Module: ModuleRegisters,
			Level:  4,
			Type:   ExerciseLesson,
			Code: []string{
				"func main() {",
				"a",
				"b",
				"c",
				"}",
			},
			CursorPos:      Position{Line: 1, Col: 0},
			Mission:        "Indent lines 2, 3 and 4 as one range with 3>>. They must read '  a', '  b' and '  c', and the braces must stay where they are.",
			Solutions:      []string{"3>>"},
			Optimal:        "3>>",
			Hint:           "A counted shift starts at the cursor, so move to the first line of the range before typing 3>>.",
			Explanation:    "The range a counted shift covers starts at the cursor and runs down for the count. Indenting the body with 3>> from line 2 leaves the surrounding braces untouched, which is why the cursor position is part of the answer.",
			TimeoutSecs:    45,
			Points:         20,
			BufferVerified: true,
		},
		// Lesson 15 (level 3): yank a range of lines and put it.
		{
			ID:     "registers_015",
			Module: ModuleRegisters,
			Level:  3,
			Type:   ExerciseLesson,
			Code: []string{
				"alpha",
				"beta",
				"gamma",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Yank lines 1 and 2 as one range with yj and put the range below line 1 with p. The buffer must read alpha, alpha, beta, beta, gamma.",
			Solutions:      []string{"yjp"},
			Optimal:        "yjp",
			Hint:           "yj is the yank operator applied to the j motion, so it yanks a whole-line range.",
			Explanation:    "A count is not the only way to name a range: yj applies the yank to the range the j motion covers, which is the current line and the one below. The linewise range is stored as whole lines and p puts both of them back at once.",
			TimeoutSecs:    45,
			Points:         15,
			BufferVerified: true,
		},
		// Lesson 16 (level 4): yank a character-wise range and put it before the cursor.
		{
			ID:     "registers_016",
			Module: ModuleRegisters,
			Level:  4,
			Type:   ExerciseLesson,
			Code: []string{
				"foo bar",
			},
			CursorPos:      Position{Line: 0, Col: 4},
			Mission:        "Yank from the cursor to the end of the line with y$, then put the range back before the cursor with P. The line must read 'foo barbar'.",
			Solutions:      []string{"y$P"},
			Optimal:        "y$P",
			Hint:           "y$ yanks a character-wise range, and P inserts it before the cursor's character.",
			Explanation:    "y$ yanks the character-wise range between the cursor and the end of the line. Because the range is character-wise rather than linewise, P inserts it in the middle of the line instead of on a line of its own -- the register's flag decides which.",
			TimeoutSecs:    45,
			Points:         20,
			BufferVerified: true,
		},
		// Lesson 17 (level 4): the unnamed register follows the last delete.
		{
			ID:     "registers_017",
			Module: ModuleRegisters,
			Level:  4,
			Type:   ExerciseLesson,
			Code: []string{
				"alpha",
				"beta",
				"gamma",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Yank line 1 with yy, then delete line 2 with j dd, then put with p. The buffer must read alpha, gamma, beta: the delete replaced the unnamed register, so p puts the deleted line, not the yank.",
			Solutions:      []string{"yyjddp"},
			Optimal:        "yyjddp",
			Hint:           "Yanks and deletes share the unnamed register, so the most recent one wins.",
			Explanation:    "yy yanks line 1 into the unnamed register, then j dd overwrites that same register with the deleted line 2. p therefore puts 'beta', not the yanked 'alpha'. The unnamed register always holds the most recent yank or delete.",
			TimeoutSecs:    45,
			Points:         20,
			BufferVerified: true,
		},
		// Lesson 18 (level 4): a named register survives another yank.
		{
			ID:     "registers_018",
			Module: ModuleRegisters,
			Level:  4,
			Type:   ExerciseLesson,
			Code: []string{
				"alpha",
				"beta",
				"gamma",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Store line 1 in register a with \"ayy, move down with j, overwrite the unnamed register with yy, then put register a with \"ap. The buffer must read alpha, beta, alpha, gamma: the named register kept the first line.",
			Solutions:      []string{"\"ayyjyy\"ap"},
			Optimal:        "\"ayyjyy\"ap",
			Hint:           "A named yank fills the named register and the unnamed one; a later unnamed yank cannot touch the named register.",
			Explanation:    "Every yank writes the unnamed register, but \"ayy also writes a, and only another command aimed at a can change a. The second yy takes the unnamed register without disturbing a, so \"ap still puts 'alpha'.",
			TimeoutSecs:    45,
			Points:         20,
			BufferVerified: true,
		},
		// Lesson 19 (level 4): a counted put.
		{
			ID:     "registers_019",
			Module: ModuleRegisters,
			Level:  4,
			Type:   ExerciseLesson,
			Code: []string{
				"alpha",
				"beta",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Yank line 1 with yy and put it twice below with 2p. The buffer must read alpha, alpha, alpha, beta.",
			Solutions:      []string{"yy2p"},
			Optimal:        "yy2p",
			Hint:           "p takes a count: 2p puts the register's contents twice.",
			Explanation:    "A count in front of p repeats the put that many times, inserting the whole register each time. 2p is how you duplicate a line three times in one command instead of typing p twice.",
			TimeoutSecs:    45,
			Points:         20,
			BufferVerified: true,
		},
		// Lesson 20 (level 5): a yank and an insert working together.
		{
			ID:     "registers_020",
			Module: ModuleRegisters,
			Level:  5,
			Type:   ExerciseLesson,
			Code: []string{
				"start",
				"end",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Yank line 1 with yy, put the copy below with p, then append ' done' to the copy with A. The buffer must read start, 'start done', end with the cursor on the last character of the edited line.",
			Solutions:      []string{"yypA done<Esc>"},
			Optimal:        "yypA done<Esc>",
			Hint:           "Put the copy first, then edit it: A appends at the end of the line the cursor is on.",
			Explanation:    "The register gives you the duplicate; the insert gives you the edit. Because yyp leaves the cursor on the copy, A appends to the copy rather than to the original, and the two commands compose without ever moving the cursor by hand.",
			TimeoutSecs:    45,
			Points:         25,
			BufferVerified: true,
		},
	}
}

func getRegistersBoss() *BossExercise {
	return &BossExercise{
		ID:        "registers_boss",
		Module:    ModuleRegisters,
		Name:      "The Archivist",
		Lives:     3,
		BonusTime: 30,
		Steps: []BossStep{
			{
				TimeLimit: 8,
				Exercise: Exercise{
					ID:     "registers_boss_1",
					Module: ModuleRegisters,
					Level:  5,
					Type:   ExerciseBoss,
					Code: []string{
						"one",
						"two",
						"three",
					},
					CursorPos:      Position{Line: 1, Col: 0},
					Mission:        "Move line 2 to the top with dd, k and P, then indent it with >>. The buffer must read '  two', one, three with the cursor on the first non-blank of the indented line.",
					Solutions:      []string{"ddkP>>"},
					Optimal:        "ddkP>>",
					Points:         50,
					BufferVerified: true,
				},
			},
			{
				TimeLimit: 10,
				Exercise: Exercise{
					ID:     "registers_boss_2",
					Module: ModuleRegisters,
					Level:  6,
					Type:   ExerciseBoss,
					Code: []string{
						"x = a",
						"y = b",
					},
					CursorPos:      Position{Line: 0, Col: 4},
					Mission:        "Yank the word 'a' with yiw, delete the line below with j dd, then put register 0 before the cursor with \"0P. The line must read 'ax = a': register 0 kept the yank while the delete took the unnamed register.",
					Solutions:      []string{"yiwjdd\"0P"},
					Optimal:        "yiwjdd\"0P",
					Points:         50,
					BufferVerified: true,
				},
			},
			{
				TimeLimit: 10,
				Exercise: Exercise{
					ID:     "registers_boss_3",
					Module: ModuleRegisters,
					Level:  6,
					Type:   ExerciseBoss,
					Code: []string{
						"    alpha",
						"beta",
					},
					CursorPos:      Position{Line: 0, Col: 0},
					Mission:        "Store line 1 in register a with \"ayy, move down with j, put it below line 2 with \"ap, then dedent the put copy with <<. The buffer must read '    alpha', beta, '  alpha'.",
					Solutions:      []string{"\"ayyj\"ap<<"},
					Optimal:        "\"ayyj\"ap<<",
					Points:         50,
					BufferVerified: true,
				},
			},
			{
				TimeLimit: 12,
				Exercise: Exercise{
					ID:     "registers_boss_4",
					Module: ModuleRegisters,
					Level:  7,
					Type:   ExerciseBoss,
					Code: []string{
						"start",
						"end",
					},
					CursorPos:      Position{Line: 0, Col: 0},
					Mission:        "Move line 1 below line 2 with dd and p, then append '!' to the moved line with A. The buffer must read end, 'start!'.",
					Solutions:      []string{"ddpA!<Esc>"},
					Optimal:        "ddpA!<Esc>",
					Points:         50,
					BufferVerified: true,
				},
			},
			{
				TimeLimit: 15,
				Exercise: Exercise{
					ID:     "registers_boss_5",
					Module: ModuleRegisters,
					Level:  8,
					Type:   ExerciseBoss,
					Code: []string{
						"alpha",
						"beta",
						"gamma",
					},
					CursorPos:      Position{Line: 0, Col: 0},
					Mission:        "Yank line 1 into register a with \"ayy, yank line 2 with j yy, delete line 3 with j dd, then put register a with \"ap and register 0 with \"0p. The buffer must read alpha, beta, alpha, beta.",
					Solutions:      []string{"\"ayyjyyjdd\"ap\"0p"},
					Optimal:        "\"ayyjyyjdd\"ap\"0p",
					Points:         50,
					BufferVerified: true,
				},
			},
		},
	}
}
