package trainer

// =============================================================================
// MACROS MODULE EXERCISES
// =============================================================================

func getMacrosLessons() []Exercise {
	return []Exercise{
		// Lesson 1: qa - start recording to register a
		{
			ID:     "macros_001",
			Module: ModuleMacros,
			Level:  1,
			Type:   ExerciseLesson,
			Code: []string{
				"item1: value1",
				"item2: value2",
				"item3: value3",
				"item4: value4",
			},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Start recording a macro to register 'a' using qa",
			Solutions:   []string{"qa"},
			Optimal:     "qa",
			Hint:        "q followed by a register letter (a-z) starts recording",
			Explanation: "qa starts recording all your keystrokes to register 'a'. Macros are Vim's way of recording and playing back keystrokes - like a tape recorder for your editing!",
			TimeoutSecs: 30,
			Points:      10,
		},
		// Lesson 2: qa - more practice
		{
			ID:     "macros_002",
			Module: ModuleMacros,
			Level:  1,
			Type:   ExerciseLesson,
			Code: []string{
				"const a = 1;",
				"const b = 2;",
				"const c = 3;",
				"const d = 4;",
			},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Start recording a macro to register 'a' (this will record edits)",
			Solutions:   []string{"qa"},
			Optimal:     "qa",
			Hint:        "Press q then a to begin recording to register a",
			Explanation: "Once you press qa, every keystroke you make will be recorded until you press q again. This is the foundation of automation in Vim.",
			TimeoutSecs: 30,
			Points:      10,
		},
		// Lesson 3: q - stop recording
		{
			ID:     "macros_003",
			Module: ModuleMacros,
			Level:  1,
			Type:   ExerciseLesson,
			Code: []string{
				"[RECORDING @a]",
				"const item = getValue();",
			},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Stop the macro recording with q",
			Solutions:   []string{"q"},
			Optimal:     "q",
			Hint:        "q stops a recording in either register, so the same key ends it wherever it started.",
			Explanation: "Pressing q while recording stops the recording. Your macro is now saved in register 'a' and ready to be played back.",
			TimeoutSecs: 30,
			Points:      10,
		},
		// Lesson 4: q - stop recording (reinforcement)
		{
			ID:     "macros_004",
			Module: ModuleMacros,
			Level:  1,
			Type:   ExerciseLesson,
			Code: []string{
				"[RECORDING @b]",
				"line one",
				"line two",
			},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "You're recording to register 'b'. Stop the recording.",
			Solutions:   []string{"q"},
			Optimal:     "q",
			Hint:        "q stops any recording regardless of the register",
			Explanation: "Remember: qa starts recording to 'a', qb to 'b', etc. A single q stops any recording. The register letter is only needed to start.",
			TimeoutSecs: 30,
			Points:      10,
		},
		// Lesson 5: @a - play macro from register a
		{
			ID:     "macros_005",
			Module: ModuleMacros,
			Level:  2,
			Type:   ExerciseLesson,
			Code: []string{
				"TODO item 1",
				"TODO item 2",
				"TODO item 3",
			},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Play the macro stored in register 'a' using @a",
			Solutions:   []string{"@a"},
			Optimal:     "@a",
			Hint:        "@a takes a count: 3@a plays register a three times in one command.",
			Explanation: "@ executes the macro stored in a register. If you recorded 'dwj' in register 'a', @a will delete a word and move down - exactly what you recorded!",
			TimeoutSecs: 30,
			Points:      15,
		},
		// Lesson 6: @a - play macro (reinforcement)
		{
			ID:     "macros_006",
			Module: ModuleMacros,
			Level:  2,
			Type:   ExerciseLesson,
			Code: []string{
				"old_name = value1",
				"old_name = value2",
				"old_name = value3",
			},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Execute the macro in register 'a' to transform this line",
			Solutions:   []string{"@a"},
			Optimal:     "@a",
			Hint:        "A count before it plays the macro more than once: 3@a is three runs.",
			Explanation: "Macros are perfect for repetitive edits. Record once, play many times. The key insight: make your macro work on ONE line, then repeat it.",
			TimeoutSecs: 30,
			Points:      15,
		},
		// Lesson 7: @@ - repeat last macro
		{
			ID:     "macros_007",
			Module: ModuleMacros,
			Level:  2,
			Type:   ExerciseLesson,
			Code: []string{
				"item1: done",
				"item2: pending",
				"item3: pending",
				"item4: pending",
			},
			CursorPos:   Position{Line: 1, Col: 0},
			Mission:     "Repeat the last macro you just played using @@",
			Solutions:   []string{"@@"},
			Optimal:     "@@",
			Hint:        "@@ plays the last macro again; 3@@ runs it three more times.",
			Explanation: "@@ is a shortcut to repeat the last macro you executed. Much faster than typing @a again! Works with any register that was last used.",
			TimeoutSecs: 30,
			Points:      15,
		},
		// Lesson 8: @@ - repeat last macro (reinforcement)
		{
			ID:     "macros_008",
			Module: ModuleMacros,
			Level:  2,
			Type:   ExerciseLesson,
			Code: []string{
				"row1 = transform(data1);",
				"row2 = transform(data2);",
				"row3 = transform(data3);",
			},
			CursorPos:   Position{Line: 1, Col: 0},
			Mission:     "Apply the same macro again with @@",
			Solutions:   []string{"@@"},
			Optimal:     "@@",
			Hint:        "@@ plays the register used last, so after @a it means @a again.",
			Explanation: "The @@ command is essential for rapid macro application. Pattern: @a to play once, then @@ @@ @@ for subsequent lines.",
			TimeoutSecs: 30,
			Points:      15,
		},
		// Lesson 9: 5@a - play macro 5 times
		{
			ID:     "macros_009",
			Module: ModuleMacros,
			Level:  3,
			Type:   ExerciseLesson,
			Code: []string{
				"line 1 - needs fix",
				"line 2 - needs fix",
				"line 3 - needs fix",
				"line 4 - needs fix",
				"line 5 - needs fix",
			},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Play macro 'a' five times in one command using 5@a",
			Solutions:   []string{"5@a"},
			Optimal:     "5@a",
			Hint:        "Prefix @ with a count to repeat multiple times",
			Explanation: "Like most Vim commands, @ accepts a count. 5@a runs the macro 5 times. Perfect for applying the same edit to many lines at once!",
			TimeoutSecs: 30,
			Points:      20,
		},
		// Lesson 10: Count with macro (reinforcement)
		{
			ID:     "macros_010",
			Module: ModuleMacros,
			Level:  3,
			Type:   ExerciseLesson,
			Code: []string{
				"data[0] = input[0];",
				"data[1] = input[1];",
				"data[2] = input[2];",
				"data[3] = input[3];",
				"data[4] = input[4];",
				"data[5] = input[5];",
				"data[6] = input[6];",
				"data[7] = input[7];",
				"data[8] = input[8];",
				"data[9] = input[9];",
			},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Apply macro 'a' to all 10 lines with 10@a",
			Solutions:   []string{"10@a"},
			Optimal:     "10@a",
			Hint:        "Use count before @ to run multiple times",
			Explanation: "Pro tip: if you have 100 lines, just use 100@a. If the macro fails partway (e.g., end of file), it stops safely. Overestimating is fine!",
			TimeoutSecs: 30,
			Points:      20,
		},
		// Lesson 11: "ay - yank to register a
		{
			ID:     "macros_011",
			Module: ModuleMacros,
			Level:  4,
			Type:   ExerciseLesson,
			Code: []string{
				"const importantValue = 'remember_this';",
				"",
				"// Need this value below",
			},
			CursorPos:      Position{Line: 0, Col: 6},
			Mission:        "Store the word 'importantValue' in register 'a' with \"ayiw, then put it on the blank line below with \"ap. The buffer must show the original line, then 'importantValue', then the comment, with the cursor on the put word's last character.",
			Solutions:      []string{"\"ayiwj\"ap"},
			Optimal:        "\"ayiwj\"ap",
			Hint:           "Register a holds the text until you overwrite it, so \"ap still puts 'importantValue' after other yanks.",
			Explanation:    "Registers aren't just for macros! \"a before any yank/delete stores that text in register 'a', and \"ap puts it back. You have 26 named registers (a-z) to use. The put on the line below is what makes the named register observable: the word it holds appears in the buffer.",
			TimeoutSecs:    30,
			Points:         25,
			BufferVerified: true,
		},
		// Lesson 12: "ap - paste from register a
		{
			ID:     "macros_012",
			Module: ModuleMacros,
			Level:  4,
			Type:   ExerciseLesson,
			Code: []string{
				"myFunction",
				"const result = ();",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Store line 1 in register 'a' with \"ayy, move down with j, then put it below the second line with \"ap. The buffer must show 'myFunction', then 'const result = ();', then 'myFunction' again.",
			Solutions:      []string{"\"ayyj\"ap"},
			Optimal:        "\"ayyj\"ap",
			Hint:           "A named register is independent of the unnamed one, so \"ap still holds this line after other yanks.",
			Explanation:    "\"ap pastes from register 'a'. Unlike the default register, which gets overwritten often, named registers (a-z) persist until you overwrite them, so \"ayy followed by \"ap is a safe round trip. The put is what makes the register observable in the buffer.",
			TimeoutSecs:    30,
			Points:         25,
			BufferVerified: true,
		},
		// Lesson 13: "+y - yank to system clipboard
		{
			ID:     "macros_013",
			Module: ModuleMacros,
			Level:  5,
			Type:   ExerciseLesson,
			Code: []string{
				"const API_KEY = 'abc123xyz789';",
				"",
				"// Copy the key to share externally",
			},
			CursorPos:      Position{Line: 0, Col: 16},
			Mission:        "Yank the string content to the clipboard register with \"+yi', then put it on the blank line below with \"+p. The buffer must show the key's content on its own line between the code line and the comment.",
			Solutions:      []string{"\"+yi'j\"+p"},
			Optimal:        "\"+yi'j\"+p",
			Hint:           "\"+ is the system clipboard register; \"+y fills it and \"+p puts it back.",
			Explanation:    "\"+ is the system clipboard! \"+y yanks to your OS clipboard so you can paste in other apps, and \"+p pastes from the clipboard into Vim. The trainer keeps the clipboard beside the unnamed register, and the put on the line below is what makes it observable in the buffer.",
			TimeoutSecs:    30,
			Points:         30,
			BufferVerified: true,
		},
		// Lesson 14: "+p - paste from system clipboard
		{
			ID:     "macros_014",
			Module: ModuleMacros,
			Level:  5,
			Type:   ExerciseLesson,
			Code: []string{
				"external_data",
				"const value = '';",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Yank the word 'external_data' to the clipboard register with \"+yiw, move to the closing quote of the empty string with j, f' and l, then put the value before it with \"+P. The buffer must read 'external_data', then 'const value = 'external_data';'.",
			Solutions:      []string{"\"+yiwjf'l\"+P"},
			Optimal:        "\"+yiwjf'l\"+P",
			Hint:           "\"+ accesses the system clipboard register; \"+y fills it and \"+P puts it before the character under the cursor.",
			Explanation:    "\"+p pastes whatever is in your system clipboard, which bridges Vim and other applications. \"+yiw fills that register with the word under the cursor, and \"+P puts it before the character under the cursor, so the value lands between the quotes. The put is what makes the clipboard observable in the buffer.",
			TimeoutSecs:    30,
			Points:         30,
			BufferVerified: true,
		},
		// Lesson 15: "0p - paste last yank (not delete)
		{
			ID:     "macros_015",
			Module: ModuleMacros,
			Level:  5,
			Type:   ExerciseLesson,
			Code: []string{
				"keep_this",
				"delete_me",
				"const target = '';",
			},
			CursorPos:      Position{Line: 0, Col: 0},
			Mission:        "Yank 'keep_this' with yiw into register 0, delete the middle line with jdd, then put register 0 between the quotes with f', l and \"0P. The buffer must read 'keep_this', then 'const target = 'keep_this';'.",
			Solutions:      []string{"yiwjddf'l\"0P"},
			Optimal:        "yiwjddf'l\"0P",
			Hint:           "\"0 is the yank register - it only stores yanked text, never deleted text.",
			Explanation:    "\"0 is the yank register! It always contains your last yank, unaffected by deletes, so after jdd the unnamed register holds 'delete_me' while \"0P still puts the yanked 'keep_this'. This solves the problem of 'I yanked something but then deleted and lost it', and the put between the quotes is what makes it observable in the buffer.",
			TimeoutSecs:    30,
			Points:         30,
			BufferVerified: true,
		},
		// Lessons 16-17: :normal - execute normal mode commands
		{
			ID:     "macros_016",
			Module: ModuleMacros,
			Level:  6,
			Type:   ExerciseLesson,
			Code: []string{
				"line one",
				"line two",
				"line three",
				"line four",
			},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Type the :normal command that would add a '// ' prefix to the current line: :normal I//  (the trainer checks the keystrokes; it does not execute ex commands)",
			Solutions:   []string{":normal I// ", ":normal I// \n", ":norm I// "},
			Optimal:     ":normal I// ",
			Hint:        ":normal executes normal mode commands from the command line when Vim runs it",
			Explanation: ":normal (or :norm) executes normal-mode commands: in Vim, ':normal I// ' inserts '// ' at the beginning of the line. This is powerful when combined with ranges. The trainer checks only the keystrokes here and does not execute ex commands, so the buffer is unchanged.",
			TimeoutSecs: 35,
			Points:      30,
		},
		{
			ID:     "macros_017",
			Module: ModuleMacros,
			Level:  6,
			Type:   ExerciseLesson,
			Code: []string{
				"item1",
				"item2",
				"item3",
				"item4",
				"item5",
			},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Type the :normal command that would append a semicolon to the current line: :normal A; (the trainer checks the keystrokes; it does not execute ex commands)",
			Solutions:   []string{":normal A;", ":normal A;\n", ":norm A;"},
			Optimal:     ":normal A;",
			Hint:        "A appends at the end of the line in normal mode when Vim runs it",
			Explanation: ":normal A; appends a semicolon at the end of the current line. Think of :normal as 'pretend I pressed these keys in normal mode'; it is the bridge between Ex commands and normal mode. The trainer checks only the keystrokes here and does not execute ex commands, so the buffer is unchanged.",
			TimeoutSecs: 35,
			Points:      30,
		},
		// Lessons 18-19: :normal with range - apply to multiple lines
		{
			ID:     "macros_018",
			Module: ModuleMacros,
			Level:  6,
			Type:   ExerciseLesson,
			Code: []string{
				"function one()",
				"function two()",
				"function three()",
				"function four()",
			},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Type the ex command that would comment every line: :% normal I//  (the trainer checks the keystrokes; it does not execute ex commands)",
			Solutions:   []string{":% normal I// ", ":% normal I// \n", ":%norm I// "},
			Optimal:     ":% normal I// ",
			Hint:        "% means all lines, and :normal runs on each line in the range when Vim executes it",
			Explanation: ":%normal applies a normal-mode command to EVERY line in the file; the % is a range meaning all lines. This is how you do bulk edits without macros - comment entire files instantly. The trainer checks only the keystrokes here and does not execute ex commands, so the buffer is unchanged.",
			TimeoutSecs: 40,
			Points:      35,
		},
		{
			ID:     "macros_019",
			Module: ModuleMacros,
			Level:  6,
			Type:   ExerciseLesson,
			Code: []string{
				"let a = 1",
				"let b = 2",
				"let c = 3",
				"let d = 4",
				"let e = 5",
			},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Type the ex command that would append ';' to lines 2-4: :2,4 normal A; (the trainer checks the keystrokes; it does not execute ex commands)",
			Solutions:   []string{":2,4 normal A;", ":2,4 normal A;\n", ":2,4norm A;"},
			Optimal:     ":2,4 normal A;",
			Hint:        "2,4 is a range meaning lines 2 through 4",
			Explanation: "In Vim, :2,4 normal A; applies 'A;' only to lines 2, 3, and 4. Ranges in Vim: % (all), 1,10 (lines 1-10), '<,'> (visual selection), . (current line), $ (last line). The trainer checks only the keystrokes here and does not execute ex commands, so the buffer is unchanged.",
			TimeoutSecs: 40,
			Points:      35,
		},
		// Lessons 20-21: :g/pattern/normal - global command with normal
		{
			ID:     "macros_020",
			Module: ModuleMacros,
			Level:  7,
			Type:   ExerciseLesson,
			Code: []string{
				"const DEBUG = true;",
				"console.log('debug info');",
				"const value = 42;",
				"console.log('more debug');",
				"return value;",
			},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Type the ex command that would comment the lines containing 'console': :g/console/normal I//  (the trainer checks the keystrokes; it does not execute ex commands)",
			Solutions:   []string{":g/console/normal I// ", ":g/console/normal I// \n", ":g/console/norm I// "},
			Optimal:     ":g/console/normal I// ",
			Hint:        ":g takes a pattern and a command: every matching line gets it, and :v takes the ones that do not.",
			Explanation: ":g (global) is one of Vim's most powerful commands: :g/console/normal I// runs 'I// ' on every line that contains 'console'. The trainer checks only the keystrokes here and does not execute ex commands, so the buffer is unchanged.",
			TimeoutSecs: 45,
			Points:      40,
		},
		{
			ID:     "macros_021",
			Module: ModuleMacros,
			Level:  7,
			Type:   ExerciseLesson,
			Code: []string{
				"TODO: fix bug",
				"function work() {}",
				"TODO: add tests",
				"const x = 1;",
				"TODO: refactor",
			},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Type the ex command that would delete the lines containing 'TODO': :g/TODO/d (the trainer checks the keystrokes; it does not execute ex commands)",
			Solutions:   []string{":g/TODO/d", ":g/TODO/d\n", ":g/TODO/delete"},
			Optimal:     ":g/TODO/d",
			Hint:        ":g runs a command per matching line; with d the line is gone, so 3 TODO lines vanish in one pass.",
			Explanation: ":g/TODO/d deletes every line containing 'TODO' when Vim runs it; the 'd' is the Ex delete command. The trainer checks only the keystrokes here and does not execute ex commands, so the buffer is unchanged.",
			TimeoutSecs: 40,
			Points:      35,
		},
		// Lessons 22-23: :g/pattern/normal @a - combine global with macros
		{
			ID:     "macros_022",
			Module: ModuleMacros,
			Level:  7,
			Type:   ExerciseLesson,
			Code: []string{
				"error: file not found",
				"info: process started",
				"error: connection failed",
				"info: task complete",
				"error: timeout occurred",
			},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Type the ex command that would run macro 'a' on the lines containing 'error': :g/error/normal @a (the trainer checks the keystrokes; it does not execute ex commands)",
			Solutions:   []string{":g/error/normal @a", ":g/error/normal @a\n", ":g/error/norm @a"},
			Optimal:     ":g/error/normal @a",
			Hint:        ":g picks the lines and :normal types the keys on each, so the macro runs on every match.",
			Explanation: ":g/error/normal @a runs your recorded macro only on the lines matching 'error' when Vim executes it. The trainer checks only the keystrokes here and does not execute ex commands, so the buffer is unchanged.",
			TimeoutSecs: 45,
			Points:      45,
		},
		{
			ID:     "macros_023",
			Module: ModuleMacros,
			Level:  7,
			Type:   ExerciseLesson,
			Code: []string{
				"DEBUG: timestamp 001",
				"OUTPUT: result ok",
				"DEBUG: timestamp 002",
				"OUTPUT: result ok",
				"DEBUG: timestamp 003",
			},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Type the ex command that would run macro 'b' on the lines containing 'DEBUG': :g/DEBUG/normal @b (the trainer checks the keystrokes; it does not execute ex commands)",
			Solutions:   []string{":g/DEBUG/normal @b", ":g/DEBUG/normal @b\n", ":g/DEBUG/norm @b"},
			Optimal:     ":g/DEBUG/normal @b",
			Hint:        "You can use any register (a-z) with :g/pattern/normal @register",
			Explanation: "The shape :g/PATTERN/normal @MACRO runs a macro on the lines matching the pattern when Vim executes it, for example :g/^function/normal @a on the function definitions. The trainer checks only the keystrokes here and does not execute ex commands, so the buffer is unchanged.",
			TimeoutSecs: 45,
			Points:      45,
		},
		// Lesson 24: :v/pattern/command - inverse global (lines NOT matching)
		{
			ID:     "macros_024",
			Module: ModuleMacros,
			Level:  7,
			Type:   ExerciseLesson,
			Code: []string{
				"keep: important data",
				"delete: temporary",
				"keep: more data",
				"delete: garbage",
				"keep: essential",
			},
			CursorPos:   Position{Line: 0, Col: 0},
			Mission:     "Type the ex command that would delete the lines that do not contain 'keep': :v/keep/d (the trainer checks the keystrokes; it does not execute ex commands)",
			Solutions:   []string{":v/keep/d", ":v/keep/d\n", ":g!/keep/d"},
			Optimal:     ":v/keep/d",
			Hint:        ":v is inverse of :g - acts on lines NOT matching",
			Explanation: ":v (or :g!) is the inverse of :g: it operates on the lines that do NOT match, so :v/keep/d deletes everything except the lines with 'keep' when Vim runs it. The trainer checks only the keystrokes here and does not execute ex commands, so the buffer is unchanged.",
			TimeoutSecs: 45,
			Points:      40,
		},
	}
}

func getMacrosBoss() *BossExercise {
	return &BossExercise{
		ID:        "macros_boss",
		Module:    ModuleMacros,
		Name:      "The Automation Wizard",
		Lives:     3,
		BonusTime: 30,
		Steps: []BossStep{
			{
				TimeLimit: 5,
				Exercise: Exercise{
					ID:     "macros_boss_1",
					Module: ModuleMacros,
					Level:  5,
					Type:   ExerciseBoss,
					Code: []string{
						"user1: active",
						"user2: active",
						"user3: active",
						"user4: active",
						"user5: active",
					},
					CursorPos: Position{Line: 0, Col: 0},
					Mission:   "Start recording a macro to register 'a'",
					Solutions: []string{"qa"},
					Optimal:   "qa",
					Points:    50,
				},
			},
			{
				TimeLimit: 5,
				Exercise: Exercise{
					ID:     "macros_boss_2",
					Module: ModuleMacros,
					Level:  5,
					Type:   ExerciseBoss,
					Code: []string{
						"[RECORDING @a]",
						"Edits made: f:r|j",
						"Ready to stop",
					},
					CursorPos: Position{Line: 0, Col: 0},
					Mission:   "Stop the macro recording",
					Solutions: []string{"q"},
					Optimal:   "q",
					Points:    50,
				},
			},
			{
				TimeLimit: 5,
				Exercise: Exercise{
					ID:     "macros_boss_3",
					Module: ModuleMacros,
					Level:  5,
					Type:   ExerciseBoss,
					Code: []string{
						"row1: pending",
						"row2: pending",
						"row3: pending",
						"row4: pending",
						"row5: pending",
					},
					CursorPos: Position{Line: 1, Col: 0},
					Mission:   "Execute the macro in register 'a'",
					Solutions: []string{"@a"},
					Optimal:   "@a",
					Points:    50,
				},
			},
			{
				TimeLimit: 5,
				Exercise: Exercise{
					ID:     "macros_boss_4",
					Module: ModuleMacros,
					Level:  5,
					Type:   ExerciseBoss,
					Code: []string{
						"item1: done",
						"item2: done",
						"item3: pending",
						"item4: pending",
						"item5: pending",
					},
					CursorPos: Position{Line: 2, Col: 0},
					Mission:   "Apply macro 'a' to remaining 3 lines with a count",
					Solutions: []string{"3@a"},
					Optimal:   "3@a",
					Points:    50,
				},
			},
			{
				TimeLimit: 6,
				Exercise: Exercise{
					ID:     "macros_boss_5",
					Module: ModuleMacros,
					Level:  5,
					Type:   ExerciseBoss,
					Code: []string{
						"// Yank register contains: 'savedValue'",
						"// You just deleted something else",
						"const x = '';  // paste yanked value here",
					},
					CursorPos: Position{Line: 2, Col: 11},
					Mission:   "Type \"0p to paste from the yank register (the trainer checks the keystrokes; it cannot pre-fill register 0)",
					Solutions: []string{"\"0p"},
					Optimal:   "\"0p",
					Points:    50,
				},
			},
		},
	}
}
